### PR TITLE
Fixing Wrong CPU Value Affect performance

### PR DESCRIPTION
**Pull request by blakbin**
Little-endian bitmask 0F = 11110000
Little CPU = CPU0 ~ CPU3 = 0b1111 = 15
BIG CPU = CPU4 ~ CPU6 = 0b1110000 = 112
Prime CPU = CPU7 = 0b11110000 = 240

### CODE REVIEW

**Comment by ZyCromerZ** [comment]
i think
cpu7 cpu6 cpu5 cpu4 cpu3 cpu2 cpu1 cpu0

then
0 0 0 0 1 1 1 1 = 15 (cpu 0 > 3)
0 1 1 1 0 0 0 0 = 112 (cpu 4 > 6)
1 0 0 0 0 0 0 0 = 128 (cpu 7)

and

1 1 1 1 0 0 0 0 = 240 (cpu 4 > 7)

are u mean set cpu 4 to cpu 7 as prime cores?

**Comment by blakbin** [comment]
Sory im no seeing big cpu 112, i mean this
bitmasking used 0f litle endian 11110000
so if cpu 0-3
|x|x|x|x|1|1|1|1|-0000
|7|6|5|4|3|2|1|0|
= 1111 = 15
cpu 4-6
|x|1|1|1|1|0|0|0|-0
|7|6|5|4|3|2|1|0|
= 1111000 = 120

cpu7
|1|1|1|1|0|0|0|0|
|7|6|5|4|3|2|1|0|
= 11110000 = 240

already try set big cpu 120 and prime 240 with dolphin emu had fps boost

**Comment by ZyCromerZ** [comment]
im already try using taskset on termux
and the result 15(0-3) 112(4-6) 128(7)  for me
and 
120 = 3-6
240 = 4-7

if ur mean `use some lower cores for big and prime` then i got it

**Comment by blakbin** [comment]
Yes,
Imjust saying  toying with this affect performance, ive set bigcpu combined 4-7 240 and leave prime to 0 since x3pro has same type for cpu 4-7 and the result is ok. If im used default and play dolphin emu, fps drop and stuttering.

**Pull request closed without merging**
